import { StyleSheet } from 'react-native';

const Styles = StyleSheet.create({
  text: {
    fontSize: 50,
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  header: {
    width: "100%",
    height: "8%",
    backgroundColor: "#2196F3",
    justifyContent: "center",
    alignItems: "center",
  },

  middle: {
    backgroundColor: "lightgrey",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "82%",
  },

  body: {
    flexDirection: 'row',
    width: "100%",
    height: "82%",
    backgroundColor: "#ADD8E6",
    flexWrap: "wrap",
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
    borderBottomColor: "black",
    borderBottomWidth: 2,
    borderTopColor: "black",
    borderTopWidth: 2,
  },

  navFooter: {
    width: "100%",
    height: "10%",
    backgroundColor: "darkgrey",
    flexWrap: "wrap",
    flexDirection: 'row',
    padding: 20,
    alignContent: "center",
    justifyContent: "space-between",
    alignItems: "center",
  },

  footer: {
    width: "100%",
    height: "10%",
    backgroundColor: "darkgrey",
    flexWrap: "wrap",
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  board: {
    width: 300,
    height: 300,
    borderWidth: 12,
    flexWrap: 'wrap',
    backgroundColor: '#ADD8E6',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  box: {
    borderWidth: 1,
    backgroundColor: 'white',
    width: 80,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  undo: {
    borderWidth: 1,
    fontSize: 30,
    backgroundColor: 'pink',
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    textAlign: "center",
  },
  redo: {
    borderWidth: 1,
    fontSize: 30,
    backgroundColor: 'orange',
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
    textAlign: "center",
  },
  loadGame: {
    borderRadius: 10,
    flex: 1,
    width: "80%",
    marginVertical: 10,
    marginHorizontal: "10%",
    backgroundColor: "darkgrey",
    alignContent: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  loadGameText: {
    fontSize: 15,
  },
  loadGameHeader: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    marginVertical: 10,
    backgroundColor: "darkgrey",
    flexWrap: "wrap",
    alignContent: "center",
    justifyContent: "space-around",
    alignItems: "center",
  },
  loadGameBody: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    marginVertical: 10,
    backgroundColor: "darkgrey",
    flexWrap: "wrap",
    alignContent: "center",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  loadGameFooter: {
    flex: 1,
    flexDirection: "row",
    width: "100%",
    marginVertical: 10,
    backgroundColor: "darkgrey",
    flexWrap: "wrap",
    alignContent: "center",
    justifyContent: "space-evenly",
    alignItems: "center",
  },
  loadGameButton: {
    borderWidth: 1,
    width: 70,
    height: 25,
    borderRadius: 10,
    textAlign: "center",
    textAlignVertical: "center",
    backgroundColor: 'lightgreen',
  }
});

export default Styles;